service: process-s3-file-to-sqs

frameworkVersion: "2"

custom:
  bucket: mpelekh-todos-bucket

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  memorySize: 128
  environment:
    QUEUE_URL: { Ref: S3Queue }
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: Allow
      Action:
        - "sqs:SendMessage"
      Resource: arn:aws:sqs:*:*:S3Queue

functions:
  process:
    handler: s3/process.process
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .json
resources:
  Resources:
    S3Queue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "S3Queue"